### ISSUE TITLE
Linux compatibility issue with Get-CIF3Config

### ISSUE THREAD

**Issue by mabaumgartner** [renisac/CIF3-pwsh#12]
When running the CIF3 module on Linux the API keys are not imported correctly when the module initializes using the `Get-CIF3Config` function.  The client config is functional after using `Set-CIF3Config` but once the shell is closed, all future imports of the client config do not supply the API keys as specified in .cif.yml.

Steps to Reproduce from a new Linux shell without any CIF3 client config defined:
1. Import-Module CIF3
1. Set-CIF3Config -Uri *URI* -Token *Token* -ReadToken *Token*
1. Confirm correct config with Get-CIF3Config
1.  Close out of shell
1. Start new shell and import CIF3 module
1. Get-CIF3Config

The `token` and `read token` values now seem to be imported incorrectly.

```
PS > Get-CIF3Config

Name                           Value
----                           -----
Uri                            https://example.com
ForceVerbose                   False
NoVerifySsl                    True
Token                          ��!
Proxy                          
WriteToken                     
ReadToken                      ��!
```

This seems to be an issue with the Decrypt function within `Get-CIF3Config`.  It works differently in a non-Windows environment as you might expect.

**Comment by mabaumgartner** [comment]
Since the Encrypt/Decrypt features are only supported on Windows per the help documentation, perhaps just adding a check to verify the Platform before running the Decrypt function would work?

```ps1
function Decrypt {
            param($String)
            try {
                if ([System.Environment]::OSVersion.Platform -eq 'Win32NT') {
                    $SecureString = ConvertTo-SecureString $String -ErrorAction Stop
                    if ($SecureString -is [System.Security.SecureString]) {
                        [System.Runtime.InteropServices.marshal]::PtrToStringAuto(
                            [System.Runtime.InteropServices.marshal]::SecureStringToBSTR(
                                $SecureString))
                    }
                }
                else {
                    return $String
                }
            }
            catch {
                # If not a SecureString, just return the regular String value
                return $String
            }
        }
```

**Comment by mdavis332** [comment]
@mabaumgartner thanks for the find! I can't believe it wasn't already on Decrypt -- looks like I had it on the encrypt side: https://github.com/renisac/CIF3-pwsh/blob/master/Public/Set-CIF3Config.ps1#L90

Also, I swear I've tested this on linux, but perhaps not since we made the last round of tweaks around the Decrypt function. 

Do you want to take a stab at fixing the Decrypt function using a similar conditional to what's present on the Encrypt side?

**Comment by mabaumgartner** [comment]
Yeah it could have been introduced with the previous changes.  Interestingly enough the URI makes it through the Decrypt function just fine, but the 80 character API keys for some reason unknown to me must look like a valid secure string on Linux (but not on Windows).

I looked at line 90 in the Encrypt function too.  It seems that `$env:OS` is only available on Windows but the `[System.Environment]::OSVersion.Platform` from above, seems cross platform in my testing.  Any reason to test for an empty string in the Decrypt function?

Happy to do a PR.

**Comment by mdavis332** [comment]
> Any reason to test for an empty string in the Decrypt function?

Not that I can immediately think of. If you imagine a scenario there, probably makes sense to account for that. 

> Happy to do a PR.

Go for it!

**Comment by mdavis332** [comment]
Thanks for the PR @mabaumgartner ! I've also adjusted the Encrypt function to use the same OS check you used here. Do you want to verify everything works as expected on your side before we close this issue and cut a new release to PSGallery?

**Comment by mabaumgartner** [comment]
Finished some testing of the main functions on both Windows and Linux yesterday evening.   Near as I can tell everything is working as expected.  I'd say if all looks good to you we're good to proceed.  Thanks for the help @mdavis332 !

**Comment by mdavis332** [comment]
Perfect, v0.9.8 has been released on GH and to the PSGallery. Thank you again @mabaumgartner!
