### ISSUE TITLE
Enhancement request: Support for write tokens

### ISSUE THREAD

**Issue by JesseBowling** [renisac/CIF3-pwsh#9]
Currently only read token support is enabled; a couple places it would be useful to have write token support would be on ping as well as submitting indicators.

**Comment by Geogboe** [comment]
@JesseBowling. I'm happy to tackle this if no one else is available! Just let me know. I do still need to get caught up on the code base though so I understand the request a bit more

**Comment by JesseBowling** [comment]
@Geogboe go forth and do great things.

**Comment by mdavis332** [comment]
i think this has been satisified by PR #10. thanks @mabaumgartner!
